source 'https://rubygems.org'

# THOR: http://rubydoc.info/github/wycats/thor/master/Thor/Actions 

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
#gem 'rails', '4.1.0'
gem 'rails', '4.0.3'
# Use mysql as the database for Active Record
gem 'mysql2' # https://github.com/brianmario/mysql2
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3' # https://github.com/rails/sass-rails
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0' # https://github.com/lautis/uglifier
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0' # https://github.com/rails/coffee-rails
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails' # https://github.com/indirect/jquery-rails
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks' # https://github.com/rails/turbolinks
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'makena', path: 'makena'
gem 'bcrypt-ruby', :require => 'bcrypt' # https://github.com/codahale/bcrypt-ruby
gem 'carrierwave' # https://github.com/jnicklas/carrierwave
gem 'chronic' # https://github.com/mojombo/chronic/
gem 'geocoder' # https://github.com/alexreisner/geocoder
gem 'albino' # https://github.com/github/albino
gem 'bootstrap-datepicker-rails' # https://github.com/Nerian/bootstrap-datepicker-rails
gem 'd3-rails' # https://github.com/iblue/d3-rails
gem 'exifr' # https://github.com/remvee/exifr
gem 'execjs' # https://github.com/sstephenson/execjs
gem 'iconv' # https://github.com/nurse/iconv
# rake figaro:heroku
# cp ../last_success/config/application.yml config/application.yml
gem 'figaro' # https://github.com/laserlemon/figaro
gem 'fog' # https://github.com/fog/fog
gem 'gherkin' # https://github.com/cucumber/gherkin
gem 'gmail' # https://github.com/nu7hatch/gmail
gem 'heroku' # https://github.com/heroku/heroku
gem 'jquery_mobile_rails' # https://github.com/dmarkow/jquery-mobile-rails
gem 'jquery-ui-rails' # https://github.com/joliss/jquery-ui-rails
gem 'json' #, '1.6.6' # https://github.com/flori/json
gem 'mandrill-rails' # https://github.com/evendis/mandrill-rails
gem 'nokogiri' # https://github.com/sparklemotion/nokogiri
gem 'numbers_in_words' # https://github.com/markburns/numbers_in_words
gem 'paypal-ipn', :require => 'paypal' # https://github.com/dwilkie/paypal
gem 'pg' # https://github.com/kamk/pg
gem 'postgres-pr' # https://github.com/mneumann/postgres-pr
gem 'phonegap-rails' # https://github.com/joscas/phonegap-rails
# rails g phonegap_rails:install
# rake phonegap:rails:android:create
# rake phonegap:rails:android:initall
gem 'rack' # https://github.com/chneukirchen/rack
gem 'rails_autolink' # https://github.com/tenderlove/rails_autolink
gem 'redcarpet', '1.17.2' # https://github.com/vmg/redcarpet
gem 'roadie' # https://github.com/Mange/roadie
gem 'rmagick' #...
gem 'sanitize' # https://github.com/rgrove/sanitize
gem 'sinatra' # https://github.com/sinatra/sinatra
gem 'therubyracer' # https://github.com/cowboyd/therubyracer
gem 'thin' # https://github.com/macournoyer/thin
gem 'twilio-ruby' # https://github.com/twilio/twilio-ruby
gem 'foreman'
gem 'unicorn'
gem 'will_paginate'
# https://github.com/mislav/will_paginate/wiki
# http://railscasts.com/episodes/240-search-sort-paginate-with-ajax?view=asciicast

group :development do

  gem 'heroku_san' # http://pivotallabs.com/users/ken/blog/articles/2056-dry-devops-with-heroku-san
  gem 'nifty-generators' # https://github.com/ryanb/nifty-generators
  gem 'pry-plus' # https://github.com/rking/pry-plus
  gem 'railroady' # https://github.com/preston/railroady

end

# BUNDLE bundle --without staging production
group :development, :test do

  gem 'pry' # https://github.com/pry/pry
  gem 'rspec' # https://github.com/rspec/rspec`
  gem 'rspec-rails' # https://github.com/rspec/rspec-rails

end

group :test do

  #gem 'minitest'
  #gem 'shoulda-matchers'
  gem 'autotest-rails' # https://github.com/seattlerb/autotest-rails
  gem 'capybara' # https://github.com/jnicklas/capybara
  gem 'cucumber' # https://github.com/cucumber/cucumber # https://github.com/cucumber/cucumber/wiki/Ruby-on-Rails
  gem 'cucumber-rails', :require => false # https://github.com/cucumber/cucumber-rails
  gem 'database_cleaner' # https://github.com/bmabey/database_cleaner
  gem 'escape_utils' # https://github.com/brianmario/escape_utils
  gem 'launchy' # https://github.com/copiousfreetime/launchy
  gem 'letter_opener' # https://github.com/ryanb/letter_opener
  gem 'pickle' # https://github.com/ianwhite/pickle
  gem 'selenium-webdriver'
  gem 'spork', '> 0.9.0.rc' # https://github.com/sporkrb/spork
  gem 'simplecov', :require => false # https://github.com/colszowka/simplecov
  gem 'turn', '< 0.8.3', :require => false # https://github.com/TwP/turn
  gem 'webrat' # https://github.com/brynary/webrat
  gem 'ZenTest' # https://github.com/seattlerb/zentest
  gem "mocha" # https://github.com/visionmedia/mocha

end

# BUNDLE bundle --without staging production
group :production, :staging do

  gem 'rails_12factor' # https://devcenter.heroku.com/articles/rails-integration-gems
  gem 'newrelic_rpm' # https://github.com/newrelic/rpm
  gem 'pry' # https://github.com/pry/pry

end

